export default class CastUnitComponentDatas {
  static cellStyle = (grid) => {
    const style = {};
    if (grid.data[grid.colDef.field + 'Red'] ) { style.color = '#FC563B';  }
    return style;
  };

  static columnDefs=[
    {
      colId: 'mtlNo',
      field: 'mtlNo',
      headerName: '강번',
      pinned: 'left',
      width: 70,
      suppressSizeToFit: true,
      sortable: false,
      rowSpan() { return 2; },
      //cellClass: 'headCell',
      cellClassRules: { 'cell-blank': params => params.value === undefined },
    }, {
      colId: 'indiMtlNo',
      field: 'indiMtlNo',
      headerName: '지시강번',
      pinned: 'left',
      width: 70,
      suppressSizeToFit: true,
      sortable: false,
      rowSpan() { return 2; },
      //cellClass: 'headCell',
      cellClassRules: { 'cell-blank': params => params.value === undefined },

    }, {
      colId: 'smSteelGrdN',
      field: 'smSteelGrdN',
      headerName: '출강목표',
      pinned: 'left',
      width: 120,
      suppressSizeToFit: true,
      sortable: false,
      rowSpan() { return 2; },
      //cellClass: 'headCell',
      cellClassRules: { 'cell-blank': params => params.value === undefined },
    }, {
      // colId:'ctlIndiCastTrChCnt',
      // field:'ctlIndiCastTrChCnt',
      colId: 'chCnt',
      field: 'chCnt',
      headerName: '작업순서',
      pinned: 'left',
      sortable: false,
      rowSpan() { return 2; },
      //cellClass: 'headCell',
      cellClassRules: { 'cell-blank': params => params.value === undefined },
      width: 70,
      suppressSizeToFit: true,
    }, {
      colId: 'smAyfeLcDestF',
      field: 'smAyfeLcDestF',
      headerName: '성분상이',
      pinned: 'left',
      width: 70,
      suppressSizeToFit: true,
      sortable: false,
      rowSpan() { return 2; },
      //cellClass: 'headCell',
      cellClassRules: { 'cell-blank': params => params.value === undefined },
      cellStyle(grid) {
        const style = {};
        if (grid.value ) { style.color = '#FC563B';  }
        return style;
      },
    }, {
      colId: 'sortation', //지시,요령
      field: 'sortation',
      headerName: '구분',
      pinned: 'left',
      sortable: false,
      width: 70,
      suppressSizeToFit: true,
      //cellClass: 'headCell',
    },


    {
      colId: 'loc1',
      field: 'loc1',
      headerName: 'C',
      children: [{
        colId: 'C',
        field: 'C',
        headerName: '%',
        width: 100,
        suppressSizeToFit: true,
        cellStyle: (grid) => this.cellStyle(grid),
      }],
    },
    {
      colId: 'loc2',
      field: 'loc2',
      headerName: 'Si',
      children: [{
        colId: 'Si',
        field: 'Si',
        headerName: '%',
        width: 100,
        suppressSizeToFit: true,
        cellStyle: (grid) => this.cellStyle(grid),
      }],
    },
    {
      colId: 'loc3',
      field: 'loc3',
      headerName: 'Mn',
      children: [{
        colId: 'Mn',
        field: 'Mn',
        headerName: '%',
        width: 100,
        suppressSizeToFit: true,
        cellStyle: (grid) => this.cellStyle(grid),
      }],
    },
    {
      colId: 'loc4',
      field: 'loc4',
      headerName: 'P',
      children: [{
        colId: 'P',
        field: 'P',
        headerName: '%',
        width: 100,
        suppressSizeToFit: true,
        cellStyle: (grid) => this.cellStyle(grid),
      }],
    },
    {
      colId: 'loc5',
      field: 'loc5',
      headerName: 'S',
      children: [{
        colId: 'S',
        field: 'S',
        headerName: '%',
        width: 100,
        suppressSizeToFit: true,
        cellStyle: (grid) => this.cellStyle(grid),
      }],
    },
    {
      colId: 'loc6',
      field: 'loc6',
      headerName: 'Sal',
      children: [{
        colId: 'Sal',
        field: 'Sal',
        headerName: '%',
        width: 100,
        suppressSizeToFit: true,
        cellStyle: (grid) => this.cellStyle(grid),
      }],
    },
    {
      colId: 'loc7',
      field: 'loc7',
      headerName: 'Tal',
      children: [{
        colId: 'Tal',
        field: 'Tal',
        headerName: '%',
        width: 100,
        suppressSizeToFit: true,
        cellStyle: (grid) => this.cellStyle(grid),
      }],
    },
    {
      colId: 'loc8',
      field: 'loc8',
      headerName: 'Cu',
      children: [{
        colId: 'Cu',
        field: 'Cu',
        headerName: '%',
        width: 100,
        suppressSizeToFit: true,
        cellStyle: (grid) => this.cellStyle(grid),
      }],
    },
    {
      colId: 'loc9',
      field: 'loc9',
      headerName: 'Nb',
      children: [{
        colId: 'Nb',
        field: 'Nb',
        headerName: '%',
        width: 100,
        suppressSizeToFit: true,
        cellStyle: (grid) => this.cellStyle(grid),
      }],
    },
    {
      colId: 'loc10',
      field: 'loc10',
      headerName: 'B',
      children: [{
        colId: 'B',
        field: 'B',
        headerName: 'ppm',
        width: 100,
        suppressSizeToFit: true,
        cellStyle: (grid) => this.cellStyle(grid),
      }],
    },
    {
      colId: 'loc11',
      field: 'loc11',
      headerName: 'Ni',
      children: [{
        colId: 'Ni',
        field: 'Ni',
        headerName: '%',
        width: 100,
        suppressSizeToFit: true,
        cellStyle: (grid) => this.cellStyle(grid),
      }],
    },
    {
      colId: 'loc12',
      field: 'loc12',
      headerName: 'Cr',
      children: [{
        colId: 'Cr',
        field: 'Cr',
        headerName: '%',
        width: 100,
        suppressSizeToFit: true,
        cellStyle: (grid) => this.cellStyle(grid),
      }],
    },
    {
      colId: 'loc13',
      field: 'loc13',
      headerName: 'Mo',
      children: [{
        colId: 'Mo',
        field: 'Mo',
        headerName: '%',
        width: 100,
        suppressSizeToFit: true,
        cellStyle: (grid) => this.cellStyle(grid),
      }],
    },
    {
      colId: 'loc14',
      field: 'loc14',
      headerName: 'W',
      children: [{
        colId: 'W',
        field: 'W',
        headerName: '%',
        width: 100,
        suppressSizeToFit: true,
        cellStyle: (grid) => this.cellStyle(grid),
      }],
    },
    {
      colId: 'loc15',
      field: 'loc15',
      headerName: 'Ti',
      children: [{
        colId: 'Ti',
        field: 'Ti',
        headerName: '%',
        width: 100,
        suppressSizeToFit: true,
        cellStyle: (grid) => this.cellStyle(grid),
      }],
    },
    {
      colId: 'loc16',
      field: 'loc16',
      headerName: 'V',
      children: [{
        colId: 'V',
        field: 'V',
        headerName: '%',
        width: 100,
        suppressSizeToFit: true,
        cellStyle: (grid) => this.cellStyle(grid),
      }],
    },
    {
      colId: 'loc17',
      field: 'loc17',
      headerName: 'Zr',
      children: [{
        colId: 'Zr',
        field: 'Zr',
        headerName: '%',
        width: 100,
        suppressSizeToFit: true,
        cellStyle: (grid) => this.cellStyle(grid),
      }],
    },
    {
      colId: 'loc18',
      field: 'loc18',
      headerName: 'Pb',
      children: [{
        colId: 'Pb',
        field: 'Pb',
        headerName: '%',
        width: 100,
        suppressSizeToFit: true,
        cellStyle: (grid) => this.cellStyle(grid),
      }],
    },
    {
      colId: 'loc19',
      field: 'loc19',
      headerName: 'Sn',
      children: [{
        colId: 'Sn',
        field: 'Sn',
        headerName: '%',
        width: 100,
        suppressSizeToFit: true,
        cellStyle: (grid) => this.cellStyle(grid),
      }],
    },
    {
      colId: 'loc20',
      field: 'loc20',
      headerName: 'As',
      children: [{
        colId: 'As',
        field: 'As',
        headerName: '%',
        width: 100,
        suppressSizeToFit: true,
        cellStyle: (grid) => this.cellStyle(grid),
      }],
    },
    {
      colId: 'loc21',
      field: 'loc21',
      headerName: 'Ca',
      children: [{
        colId: 'Ca',
        field: 'Ca',
        headerName: 'ppm',
        width: 100,
        suppressSizeToFit: true,
        cellStyle: (grid) => this.cellStyle(grid),
      }],
    },
    {
      colId: 'loc22',
      field: 'loc22',
      headerName: 'Co',
      children: [{
        colId: 'Co',
        field: 'Co',
        headerName: '%',
        width: 100,
        suppressSizeToFit: true,
        cellStyle: (grid) => this.cellStyle(grid),
      }],
    },
    {
      colId: 'loc23',
      field: 'loc23',
      headerName: 'Mg',
      children: [{
        colId: 'Mg',
        field: 'Mg',
        headerName: 'ppm',
        width: 100,
        suppressSizeToFit: true,
        cellStyle: (grid) => this.cellStyle(grid),
      }],
    },
    {
      colId: 'loc24',
      field: 'loc24',
      headerName: 'Te',
      children: [{
        colId: 'Te',
        field: 'Te',
        headerName: '%',
        width: 100,
        suppressSizeToFit: true,
        cellStyle: (grid) => this.cellStyle(grid),
      }],
    },
    {
      colId: 'loc25',
      field: 'loc25',
      headerName: 'Bi',
      children: [{
        colId: 'Bi',
        field: 'Bi',
        headerName: '%',
        width: 100,
        suppressSizeToFit: true,
        cellStyle: (grid) => this.cellStyle(grid),
      }],
    },
    {
      colId: 'loc26',
      field: 'loc26',
      headerName: 'Sb',
      children: [{
        colId: 'Sb',
        field: 'Sb',
        headerName: '%',
        width: 100,
        suppressSizeToFit: true,
        cellStyle: (grid) => this.cellStyle(grid),
      }],
    },
    {
      colId: 'loc27',
      field: 'loc27',
      headerName: 'Zn',
      children: [{
        colId: 'Zn',
        field: 'Zn',
        headerName: '%',
        width: 100,
        suppressSizeToFit: true,
        cellStyle: (grid) => this.cellStyle(grid),
      }],
    },
    {
      colId: 'loc28',
      field: 'loc28',
      headerName: 'H',
      children: [{
        colId: 'H',
        field: 'H',
        headerName: 'ppm',
        width: 100,
        suppressSizeToFit: true,
        cellStyle: (grid) => this.cellStyle(grid),
      }],
    },
    {
      colId: 'loc29',
      field: 'loc29',
      headerName: 'N',
      children: [{
        colId: 'N',
        field: 'N',
        headerName: 'ppm',
        width: 100,
        suppressSizeToFit: true,
        cellStyle: (grid) => this.cellStyle(grid),
      }],
    },
    {
      colId: 'loc30',
      field: 'loc30',
      headerName: 'O',
      children: [{
        colId: 'O',
        field: 'O',
        headerName: 'ppm',
        width: 100,
        suppressSizeToFit: true,
        cellStyle: (grid) => this.cellStyle(grid),
      }],
    },
    {
      colId: 'loc31',
      field: 'loc31',
      headerName: 'Ceq',
      children: [{
        colId: 'Ceq',
        field: 'Ceq',
        headerName: '%',
        width: 100,
        suppressSizeToFit: true,
        cellStyle: (grid) => this.cellStyle(grid),
      }],
    },
    {
      colId: 'loc32',
      field: 'loc32',
      headerName: 'Pcm',
      children: [{
        colId: 'Pcm',
        field: 'Pcm',
        headerName: '%',
        width: 100,
        suppressSizeToFit: true,
        cellStyle: (grid) => this.cellStyle(grid),
      }],
    },
    {
      colId: 'loc33',
      field: 'loc33',
      headerName: 'Eti',
      children: [{
        colId: 'Eti',
        field: 'Eti',
        headerName: '%',
        width: 100,
        suppressSizeToFit: true,
        cellStyle: (grid) => this.cellStyle(grid),
      }],
    },
    {
      colId: 'loc34',
      field: 'loc34',
      headerName: 'Enb',
      children: [{
        colId: 'Enb',
        field: 'Enb',
        headerName: '%',
        width: 100,
        suppressSizeToFit: true,
        cellStyle: (grid) => this.cellStyle(grid),
      }],
    },
  ];
}
